/**
 * Relay — Drizzle ORM schema (MySQL dialect)
 * Canonical 20-table model v1.0
 *
 * Dependencies:
 *   drizzle-orm   ^0.30
 *   mysql2        ^3
 *   ulid          ^2
 *
 * All primary keys are ULID (26-char, time-ordered, URL-safe).
 * Human-readable refs (case_ref, run_ref, plan_ref) are separate columns,
 * unique per project, generated by the service layer.
 *
 * Snapshot immutability and audit-log append-only enforcement are
 * service-layer concerns. The DB schema does not enforce them directly.
 */

import {
  bigint,
  boolean,
  date,
  datetime,
  index,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  tinyint,
  unique,
  varchar,
} from 'drizzle-orm/mysql-core'
import { relations, sql } from 'drizzle-orm'
import { ulid } from 'ulid'

// ---------------------------------------------------------------------------
// Column helpers
// ---------------------------------------------------------------------------

/** ULID primary key — 26-char, time-ordered, generated at application layer. */
const id = () =>
  varchar('id', { length: 26 })
    .primaryKey()
    .$defaultFn(() => ulid())

/**
 * Standard created_at / updated_at pair.
 * MySQL TIMESTAMP type supports .onUpdateNow() via ON UPDATE CURRENT_TIMESTAMP.
 * mode: 'date' returns JS Date objects from the driver.
 */
const timestamps = {
  createdAt: timestamp('created_at', { mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { mode: 'date' })
    .notNull()
    .defaultNow()
    .onUpdateNow(),
}

// ---------------------------------------------------------------------------
// 1. organisations
//    Top-level multi-tenant scope. All other entities belong to an org
//    via their project (or directly for audit_log / attachments_metadata).
// ---------------------------------------------------------------------------

export const organisations = mysqlTable(
  'organisations',
  {
    id: id(),
    slug: varchar('slug', { length: 100 }).notNull(),
    name: varchar('name', { length: 255 }).notNull(),
    isActive: boolean('is_active').notNull().default(true),
    ...timestamps,
  },
  (t) => ({
    slugUnique: unique('org_slug_unique').on(t.slug),
  }),
)

// ---------------------------------------------------------------------------
// 2. users
//    System users scoped to an organisation.
//    NextAuth session tables (sessions, verification_tokens, accounts)
//    are managed separately by the NextAuth MySQL adapter — not defined here.
//    The NextAuth user adapter should reference this table's id column.
// ---------------------------------------------------------------------------

export const users = mysqlTable(
  'users',
  {
    id: id(),
    orgId: varchar('org_id', { length: 26 })
      .notNull()
      .references(() => organisations.id, { onDelete: 'restrict' }),
    email: varchar('email', { length: 255 }).notNull(),
    name: varchar('name', { length: 255 }).notNull(),
    /**
     * Hashed with bcrypt (cost factor 12). Never stored or logged in plaintext.
     * Nullable to support future SSO-only users who authenticate via a provider
     * and have no local password.
     */
    passwordHash: varchar('password_hash', { length: 255 }),
    globalRole: mysqlEnum('global_role', [
      'super_admin',
      'admin',
      'contributor',
      'viewer',
    ])
      .notNull()
      .default('viewer'),
    isActive: boolean('is_active').notNull().default(true),
    lastLoginAt: datetime('last_login_at', { mode: 'date' }),
    ...timestamps,
  },
  (t) => ({
    emailUnique: unique('user_email_unique').on(t.email),
    orgIdIdx: index('user_org_id_idx').on(t.orgId),
    orgRoleIdx: index('user_org_role_idx').on(t.orgId, t.globalRole),
  }),
)

// ---------------------------------------------------------------------------
// 3. projects
//    First-class workspace entity. Every test case, plan, run, and audit
//    event is scoped to a project. Deleting a project is not permitted via FK —
//    projects must be archived, never hard-deleted.
// ---------------------------------------------------------------------------

export const projects = mysqlTable(
  'projects',
  {
    id: id(),
    orgId: varchar('org_id', { length: 26 })
      .notNull()
      .references(() => organisations.id, { onDelete: 'restrict' }),
    /**
     * URL-safe slug, unique within an org.
     * e.g. "ctms", "etmf", "sso-iam"
     */
    slug: varchar('slug', { length: 100 }).notNull(),
    name: varchar('name', { length: 255 }).notNull(),
    description: text('description'),
    status: mysqlEnum('status', ['active', 'archived']).notNull().default('active'),
    createdBy: varchar('created_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    ...timestamps,
  },
  (t) => ({
    orgSlugUnique: unique('project_org_slug_unique').on(t.orgId, t.slug),
    orgIdIdx: index('project_org_id_idx').on(t.orgId),
    statusIdx: index('project_status_idx').on(t.status),
  }),
)

// ---------------------------------------------------------------------------
// 4. project_roles
//    Project-level role overrides. A user's effective role within a project
//    is MAX(users.global_role, project_roles.role) in the role hierarchy:
//      super_admin > admin > contributor > viewer
//    Job titles (e.g. QA Lead) are profile metadata — not RBAC enums.
//    Evaluated at request time by the RBAC middleware.
// ---------------------------------------------------------------------------

export const projectRoles = mysqlTable(
  'project_roles',
  {
    id: id(),
    projectId: varchar('project_id', { length: 26 })
      .notNull()
      .references(() => projects.id, { onDelete: 'cascade' }),
    userId: varchar('user_id', { length: 26 })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    role: mysqlEnum('role', ['admin', 'contributor', 'viewer']).notNull(),
    grantedBy: varchar('granted_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    grantedAt: timestamp('granted_at', { mode: 'date' }).notNull().defaultNow(),
  },
  (t) => ({
    projectUserUnique: unique('project_role_unique').on(t.projectId, t.userId),
    projectIdIdx: index('pr_project_id_idx').on(t.projectId),
    userIdIdx: index('pr_user_id_idx').on(t.userId),
  }),
)

// ---------------------------------------------------------------------------
// 5. folders
//    Hierarchical folder/suite tree for organising test cases within a project.
//    Supports arbitrary depth. MySQL 8.0 recursive CTEs traverse this via
//    WITH RECURSIVE using the parent_id self-reference.
//
//    IMPORTANT: The self-referential FK (parent_id → folders.id) is NOT
//    declared here in Drizzle to avoid circular table reference issues during
//    schema initialisation. Add it explicitly in your first migration:
//      ALTER TABLE folders
//        ADD CONSTRAINT fk_folder_parent
//        FOREIGN KEY (parent_id) REFERENCES folders(id)
//        ON DELETE RESTRICT;
//    Root-level folders have parent_id = NULL.
// ---------------------------------------------------------------------------

export const folders = mysqlTable(
  'folders',
  {
    id: id(),
    projectId: varchar('project_id', { length: 26 })
      .notNull()
      .references(() => projects.id, { onDelete: 'cascade' }),
    /**
     * NULL for root-level folders.
     * FK to folders.id is added via raw migration — see note above.
     */
    parentId: varchar('parent_id', { length: 26 }),
    name: varchar('name', { length: 255 }).notNull(),
    description: text('description'),
    /** Ordering among siblings (same parent). Managed by service layer. */
    position: int('position').notNull().default(0),
    createdBy: varchar('created_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    ...timestamps,
  },
  (t) => ({
    projectIdIdx: index('folder_project_id_idx').on(t.projectId),
    parentIdIdx: index('folder_parent_id_idx').on(t.parentId),
    projectPositionIdx: index('folder_project_position_idx').on(
      t.projectId,
      t.position,
    ),
  }),
)

// ---------------------------------------------------------------------------
// 6. test_cases
//    Core entity. Cases are never hard-deleted — only archived.
//    case_ref is a human-readable identifier unique per project (e.g. TC-1001).
//    Generated by the service layer using a per-project counter strategy
//    (see schema-rationale.md — ref counter pattern).
//
//    Tags are stored as a JSON array for MVP simplicity.
//    Extract to a normalised test_case_tags table in Phase 2.
//
//    indexed_at tracks the last time this case was written to OpenSearch.
//    NULL means it has never been indexed. Used for sync gap detection.
// ---------------------------------------------------------------------------

export const testCases = mysqlTable(
  'test_cases',
  {
    id: id(),
    /** e.g. "TC-1001" — unique within the project. */
    caseRef: varchar('case_ref', { length: 20 }).notNull(),
    projectId: varchar('project_id', { length: 26 })
      .notNull()
      .references(() => projects.id, { onDelete: 'restrict' }),
    folderId: varchar('folder_id', { length: 26 }).references(() => folders.id, {
      onDelete: 'set null',
    }),
    title: varchar('title', { length: 500 }).notNull(),
    priority: mysqlEnum('priority', [
      'critical',
      'high',
      'medium',
      'low',
    ])
      .notNull()
      .default('medium'),
    type: mysqlEnum('type', [
      'functional',
      'smoke',
      'regression',
      'integration',
      'security',
    ])
      .notNull()
      .default('functional'),
    preconditions: text('preconditions'),
    description: text('description'),
    automationStatus: mysqlEnum('automation_status', [
      'manual',
      'automated',
      'semi_automated',
    ])
      .notNull()
      .default('manual'),
    /**
     * JSON array of tag strings. e.g. ["ctms", "regression", "role-mapping"]
     * Phase 2: normalise to test_case_tags table for indexed tag search.
     * At MVP, tag filtering is handled by OpenSearch (tags field is indexed there).
     */
    tags: json('tags').$type<string[]>().default([]),
    assignedTo: varchar('assigned_to', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    createdBy: varchar('created_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    isArchived: boolean('is_archived').notNull().default(false),
    /** Ordering within the folder. Managed by service layer. */
    position: int('position').notNull().default(0),
    /** NULL = not yet indexed. Set to NOW() on each successful OpenSearch write. */
    indexedAt: datetime('indexed_at', { mode: 'date' }),
    ...timestamps,
  },
  (t) => ({
    projectRefUnique: unique('tc_project_ref_unique').on(t.projectId, t.caseRef),
    projectFolderIdx: index('tc_project_folder_idx').on(t.projectId, t.folderId),
    projectArchivedIdx: index('tc_project_archived_idx').on(
      t.projectId,
      t.isArchived,
    ),
    priorityIdx: index('tc_priority_idx').on(t.priority),
    assignedToIdx: index('tc_assigned_to_idx').on(t.assignedTo),
    /**
     * Used by the OpenSearch sync process to find cases where
     * updated_at > indexed_at (i.e. modified since last sync).
     */
    updatedAtIdx: index('tc_updated_at_idx').on(t.updatedAt),
  }),
)

// ---------------------------------------------------------------------------
// 7. test_case_steps
//    Ordered steps within a test case. Position is 1-based.
//    Steps are cascade-deleted when a case is deleted.
//    (Cases themselves are never hard-deleted at business logic level,
//     but the FK cascade is the safety net.)
// ---------------------------------------------------------------------------

export const testCaseSteps = mysqlTable(
  'test_case_steps',
  {
    id: id(),
    testCaseId: varchar('test_case_id', { length: 26 })
      .notNull()
      .references(() => testCases.id, { onDelete: 'cascade' }),
    /** 1-based step number, unique per case. Max practical limit ~50. */
    position: tinyint('position').notNull(),
    action: text('action').notNull(),
    expectedResult: text('expected_result'),
    ...timestamps,
  },
  (t) => ({
    testCaseIdIdx: index('step_test_case_id_idx').on(t.testCaseId),
    testCasePosIdx: index('step_test_case_pos_idx').on(t.testCaseId, t.position),
  }),
)

// ---------------------------------------------------------------------------
// 8. test_plans
//    Meta-objects that spawn runs. A plan is never executed directly.
//    Plans reference individual test cases (via test_plan_cases), not folders.
//    The UI groups plan cases by folder for display purposes.
//
//    assignee_ids is a JSON array of user ID strings for MVP simplicity.
//    Phase 2: normalise to a test_plan_assignees table.
// ---------------------------------------------------------------------------

export const testPlans = mysqlTable(
  'test_plans',
  {
    id: id(),
    /** e.g. "PLAN-001" — unique within the project. */
    planRef: varchar('plan_ref', { length: 20 }).notNull(),
    projectId: varchar('project_id', { length: 26 })
      .notNull()
      .references(() => projects.id, { onDelete: 'restrict' }),
    title: varchar('title', { length: 500 }).notNull(),
    description: text('description'),
    status: mysqlEnum('status', ['draft', 'active', 'archived'])
      .notNull()
      .default('draft'),
    environment: varchar('environment', { length: 100 }),
    ownerId: varchar('owner_id', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    createdBy: varchar('created_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    /**
     * JSON array of user IDs. e.g. ["01HX...", "01HY..."]
     * Phase 2: normalise to test_plan_assignees table.
     */
    assigneeIds: json('assignee_ids').$type<string[]>().default([]),
    /** NULL = not yet indexed. */
    indexedAt: datetime('indexed_at', { mode: 'date' }),
    ...timestamps,
  },
  (t) => ({
    projectRefUnique: unique('plan_project_ref_unique').on(t.projectId, t.planRef),
    projectStatusIdx: index('plan_project_status_idx').on(t.projectId, t.status),
    ownerIdIdx: index('plan_owner_id_idx').on(t.ownerId),
    updatedAtIdx: index('plan_updated_at_idx').on(t.updatedAt),
  }),
)

// ---------------------------------------------------------------------------
// 9. test_plan_cases
//    Individual test case inclusions in a plan. ON DELETE RESTRICT on
//    test_case_id prevents hard-deleting cases that are referenced by
//    active plans. Archive the case instead.
// ---------------------------------------------------------------------------

export const testPlanCases = mysqlTable(
  'test_plan_cases',
  {
    id: id(),
    testPlanId: varchar('test_plan_id', { length: 26 })
      .notNull()
      .references(() => testPlans.id, { onDelete: 'cascade' }),
    testCaseId: varchar('test_case_id', { length: 26 })
      .notNull()
      .references(() => testCases.id, { onDelete: 'restrict' }),
    /** Ordering within the plan. Default is by case position within folder. */
    position: int('position').notNull().default(0),
    addedBy: varchar('added_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    addedAt: timestamp('added_at', { mode: 'date' }).notNull().defaultNow(),
  },
  (t) => ({
    planCaseUnique: unique('tpc_plan_case_unique').on(t.testPlanId, t.testCaseId),
    testPlanIdIdx: index('tpc_test_plan_id_idx').on(t.testPlanId),
    testCaseIdIdx: index('tpc_test_case_id_idx').on(t.testCaseId),
  }),
)

// ---------------------------------------------------------------------------
// 10. test_runs
//     Spawned from a test plan. Holds run-level metadata.
//     The actual case data lives in test_run_cases (snapshot + result).
//     test_plan_id is nullable to allow future ad-hoc run creation
//     without a plan (Phase 2 feature, schema-ready now).
//
//     Run sealing: sealed_at + sealed_by are set when status → 'sealed'.
//     The service layer rejects all result mutations on sealed runs.
//     Only admin or super_admin can reopen (status → 'active').
// ---------------------------------------------------------------------------

export const testRuns = mysqlTable(
  'test_runs',
  {
    id: id(),
    /** e.g. "RUN-001" — unique within the project. */
    runRef: varchar('run_ref', { length: 20 }).notNull(),
    projectId: varchar('project_id', { length: 26 })
      .notNull()
      .references(() => projects.id, { onDelete: 'restrict' }),
    /**
     * The plan this run was spawned from. Nullable for Phase 2 ad-hoc runs.
     * SET NULL so run history is preserved if a plan is archived/deleted.
     */
    testPlanId: varchar('test_plan_id', { length: 26 }).references(
      () => testPlans.id,
      { onDelete: 'set null' },
    ),
    title: varchar('title', { length: 500 }).notNull(),
    status: mysqlEnum('status', ['active', 'stalled', 'sealed', 'archived'])
      .notNull()
      .default('active'),
    environment: varchar('environment', { length: 100 }),
    dueDate: date('due_date'),
    /**
     * Stalled is a manually-toggled flag (Admin or above).
     * Auto-detection based on inactivity is Phase 2.
     * status remains 'active' when is_stalled = true to avoid
     * conflating stalled with the sealed/archived lifecycle states.
     */
    isStalled: boolean('is_stalled').notNull().default(false),
    sealedAt: datetime('sealed_at', { mode: 'date' }),
    sealedBy: varchar('sealed_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    createdBy: varchar('created_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    /** NULL = not yet indexed. */
    indexedAt: datetime('indexed_at', { mode: 'date' }),
    ...timestamps,
  },
  (t) => ({
    projectRefUnique: unique('run_project_ref_unique').on(t.projectId, t.runRef),
    projectStatusIdx: index('run_project_status_idx').on(t.projectId, t.status),
    projectPlanIdx: index('run_project_plan_idx').on(t.projectId, t.testPlanId),
    projectStalledIdx: index('run_project_stalled_idx').on(
      t.projectId,
      t.isStalled,
    ),
    updatedAtIdx: index('run_updated_at_idx').on(t.updatedAt),
  }),
)

// ---------------------------------------------------------------------------
// 11. test_run_cases
//     One row per test case included in a run. Contains both:
//
//     SNAPSHOT COLUMNS (snapshot_*):
//       Immutable copy of the case as it existed when the run was created.
//       Set once by TestRunService.create() inside the spawn transaction.
//       Never updated after creation. Service layer enforces this.
//
//     RESULT COLUMNS (status, comment, executed_by, executed_at):
//       Mutable during execution. Locked when the parent run is sealed.
//       Pre-populated with status = 'not_run' at run creation time so
//       every case in the run always has a result row — this simplifies
//       queries (no LEFT JOIN needed to check not-run status).
//
//     ORDERING:
//       Execution case list is ordered by snapshot_priority (CRIT→LOW)
//       then by position within the run. Both are available as columns
//       to avoid sorting in application code.
//
//     testCaseId uses ON DELETE RESTRICT because cases should be archived,
//     not hard-deleted. The snapshot preserves the case content regardless,
//     but the FK back to the source case is useful for history linking.
// ---------------------------------------------------------------------------

export const testRunCases = mysqlTable(
  'test_run_cases',
  {
    id: id(),
    testRunId: varchar('test_run_id', { length: 26 })
      .notNull()
      .references(() => testRuns.id, { onDelete: 'cascade' }),
    /**
     * Reference back to the source test case.
     * RESTRICT: prevents hard-deletion of cases that have execution history.
     * The snapshot columns preserve all content independently.
     */
    testCaseId: varchar('test_case_id', { length: 26 })
      .notNull()
      .references(() => testCases.id, { onDelete: 'restrict' }),

    // ── SNAPSHOT ── immutable after creation ────────────────────────────────

    snapshotCaseRef: varchar('snapshot_case_ref', { length: 20 }).notNull(),
    snapshotTitle: varchar('snapshot_title', { length: 500 }).notNull(),
    snapshotPreconditions: text('snapshot_preconditions'),
    snapshotDescription: text('snapshot_description'),
    snapshotPriority: mysqlEnum('snapshot_priority', [
      'critical',
      'high',
      'medium',
      'low',
    ]).notNull(),
    snapshotType: mysqlEnum('snapshot_type', [
      'functional',
      'smoke',
      'regression',
      'integration',
      'security',
    ]).notNull(),
    /** Denormalised folder/suite name at snapshot time. */
    snapshotFolderName: varchar('snapshot_folder_name', { length: 255 }),
    /** Tags at snapshot time. */
    snapshotTags: json('snapshot_tags').$type<string[]>().default([]),

    // ── ASSIGNMENT ──────────────────────────────────────────────────────────

    /**
     * Case-level assignee. Inherited from the test case at snapshot time
     * and overridable within the run. Different from run_assignees which
     * holds the run-level team members.
     */
    assignedTo: varchar('assigned_to', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),

    // ── RESULT ── mutable until run is sealed ───────────────────────────────

    status: mysqlEnum('status', [
      'not_run',
      'pass',
      'fail',
      'blocked',
      'skip',
    ])
      .notNull()
      .default('not_run'),
    comment: text('comment'),
    executedBy: varchar('executed_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    executedAt: datetime('executed_at', { mode: 'date' }),

    // ── ORDERING ────────────────────────────────────────────────────────────

    /**
     * Position within the run. Combined with snapshot_priority in ORDER BY
     * to produce: CRIT → HIGH → MED → LOW, then Fail → Blocked → Not run → Pass.
     * Priority sort is done via FIELD() or CASE in the query, not stored.
     */
    position: int('position').notNull().default(0),

    ...timestamps,
  },
  (t) => ({
    runCaseUnique: unique('trc_run_case_unique').on(t.testRunId, t.testCaseId),
    runIdIdx: index('trc_run_id_idx').on(t.testRunId),
    runStatusIdx: index('trc_run_status_idx').on(t.testRunId, t.status),
    /**
     * Composite index used by the execution case list ORDER BY query.
     * ORDER BY snapshot_priority (via FIELD/CASE), position
     */
    runPriorityPosIdx: index('trc_run_priority_pos_idx').on(
      t.testRunId,
      t.snapshotPriority,
      t.position,
    ),
    assignedToIdx: index('trc_assigned_to_idx').on(t.testRunId, t.assignedTo),
  }),
)

// ---------------------------------------------------------------------------
// 12. run_case_step_snapshots
//     Immutable snapshot of each step at run creation time.
//     Created once by TestRunService.create() — never updated.
//     Preserves the action and expected_result as they were at run spawn.
//
//     originalStepId links back to the live test_case_steps row.
//     SET NULL if the original step is later deleted from the live case
//     (steps can be deleted from a case; the snapshot is unaffected).
// ---------------------------------------------------------------------------

export const runCaseStepSnapshots = mysqlTable(
  'run_case_step_snapshots',
  {
    id: id(),
    testRunCaseId: varchar('test_run_case_id', { length: 26 })
      .notNull()
      .references(() => testRunCases.id, { onDelete: 'cascade' }),
    /**
     * Nullable — the live step may be edited or deleted after snapshot.
     * The snapshot content is self-contained.
     */
    originalStepId: varchar('original_step_id', { length: 26 }).references(
      () => testCaseSteps.id,
      { onDelete: 'set null' },
    ),
    /** 1-based step number as it was at snapshot time. */
    position: tinyint('position').notNull(),
    action: text('action').notNull(),
    expectedResult: text('expected_result'),
    /**
     * Intentionally no updated_at. This row is immutable.
     * Any write attempt after creation is a bug in the service layer.
     */
    createdAt: timestamp('created_at', { mode: 'date' }).notNull().defaultNow(),
  },
  (t) => ({
    testRunCaseIdIdx: index('rcss_test_run_case_id_idx').on(t.testRunCaseId),
    testRunCasePosIdx: index('rcss_test_run_case_pos_idx').on(
      t.testRunCaseId,
      t.position,
    ),
  }),
)

// ---------------------------------------------------------------------------
// 13. run_step_results
//     Mutable step-level execution results.
//     Created on first interaction with a step during execution.
//     UNIQUE(test_run_case_id, step_snapshot_id) so upsert is safe.
//
//     Step results are informational. The canonical execution outcome is
//     the case-level status in test_run_cases.status. QA engineers set
//     the overall result manually — step results do not auto-aggregate.
// ---------------------------------------------------------------------------

export const runStepResults = mysqlTable(
  'run_step_results',
  {
    id: id(),
    testRunCaseId: varchar('test_run_case_id', { length: 26 })
      .notNull()
      .references(() => testRunCases.id, { onDelete: 'cascade' }),
    stepSnapshotId: varchar('step_snapshot_id', { length: 26 })
      .notNull()
      .references(() => runCaseStepSnapshots.id, { onDelete: 'cascade' }),
    status: mysqlEnum('status', [
      'not_run',
      'pass',
      'fail',
      'blocked',
      'skip',
    ])
      .notNull()
      .default('not_run'),
    comment: text('comment'),
    executedBy: varchar('executed_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    executedAt: datetime('executed_at', { mode: 'date' }),
    ...timestamps,
  },
  (t) => ({
    runCaseStepUnique: unique('rsr_run_case_step_unique').on(
      t.testRunCaseId,
      t.stepSnapshotId,
    ),
    testRunCaseIdIdx: index('rsr_test_run_case_id_idx').on(t.testRunCaseId),
  }),
)

// ---------------------------------------------------------------------------
// 14. run_assignees
//     Run-level team assignments. Different from case-level assignment
//     (test_run_cases.assigned_to).
//     Run assignees are the set of users responsible for this run overall —
//     shown in the dashboard run card Assignees tab and in run metadata.
// ---------------------------------------------------------------------------

export const runAssignees = mysqlTable(
  'run_assignees',
  {
    id: id(),
    testRunId: varchar('test_run_id', { length: 26 })
      .notNull()
      .references(() => testRuns.id, { onDelete: 'cascade' }),
    userId: varchar('user_id', { length: 26 })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    assignedBy: varchar('assigned_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    assignedAt: timestamp('assigned_at', { mode: 'date' }).notNull().defaultNow(),
  },
  (t) => ({
    runUserUnique: unique('ra_run_user_unique').on(t.testRunId, t.userId),
    testRunIdIdx: index('ra_test_run_id_idx').on(t.testRunId),
    userIdIdx: index('ra_user_id_idx').on(t.userId),
  }),
)

// ---------------------------------------------------------------------------
// 15. run_defect_links
//     External defect IDs linked to a specific case execution within a run.
//     defect_ref stores the external ID as-is (e.g. "TI-4419", "JIRA-123").
//     Relay does not manage the defect lifecycle — it stores the reference only.
//
//     Soft-delete: unlinked_at is set when a defect is unlinked.
//     Hard-delete is not used so the link history is preserved in audit_log.
//     The D shortcut in Test Runs adds a new row here and fires an audit event.
// ---------------------------------------------------------------------------

export const runDefectLinks = mysqlTable(
  'run_defect_links',
  {
    id: id(),
    testRunCaseId: varchar('test_run_case_id', { length: 26 })
      .notNull()
      .references(() => testRunCases.id, { onDelete: 'cascade' }),
    /** External defect reference. e.g. "TI-4419". No FK — external system. */
    defectRef: varchar('defect_ref', { length: 100 }).notNull(),
    /** Optional deep link into the external defect system. */
    defectUrl: varchar('defect_url', { length: 500 }),
    linkedBy: varchar('linked_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    linkedAt: timestamp('linked_at', { mode: 'date' }).notNull().defaultNow(),
    /** NULL = still linked. Set when the defect is unlinked. */
    unlinkedAt: datetime('unlinked_at', { mode: 'date' }),
    unlinkedBy: varchar('unlinked_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
  },
  (t) => ({
    testRunCaseIdIdx: index('rdl_test_run_case_id_idx').on(t.testRunCaseId),
    defectRefIdx: index('rdl_defect_ref_idx').on(t.defectRef),
    /** Covers the common query: active links for a case (WHERE unlinked_at IS NULL). */
    activeLinksIdx: index('rdl_active_links_idx').on(
      t.testRunCaseId,
      t.unlinkedAt,
    ),
  }),
)

// ---------------------------------------------------------------------------
// 16. run_execution_comments
//     Comments on a specific case within a specific run.
//     Separate from test case activity/comments (which are case-scoped).
//     These comments are execution-context comments — attached to the run
//     instance of the case, not the case definition itself.
//     Soft-delete via is_deleted. Content is preserved in audit_log.
// ---------------------------------------------------------------------------

export const runExecutionComments = mysqlTable(
  'run_execution_comments',
  {
    id: id(),
    testRunCaseId: varchar('test_run_case_id', { length: 26 })
      .notNull()
      .references(() => testRunCases.id, { onDelete: 'cascade' }),
    userId: varchar('user_id', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    content: text('content').notNull(),
    /** Soft delete. Content preserved; is_deleted = true hides from UI. */
    isDeleted: boolean('is_deleted').notNull().default(false),
    ...timestamps,
  },
  (t) => ({
    testRunCaseIdIdx: index('rec_test_run_case_id_idx').on(t.testRunCaseId),
    userIdIdx: index('rec_user_id_idx').on(t.userId),
    activeCommentsIdx: index('rec_active_comments_idx').on(
      t.testRunCaseId,
      t.isDeleted,
    ),
  }),
)

// ---------------------------------------------------------------------------
// 17. audit_log
//     Append-only event log. No UPDATE or DELETE queries must ever target
//     this table. Enforce via:
//       1. Service layer: AuditService.log() only ever INSERT.
//       2. IAM/DB user: grant INSERT only on audit_log to the app DB user.
//       3. Optional: MySQL trigger to block UPDATE/DELETE (add in migration).
//
//     entity_type and entity_id use varchar (not FK) intentionally.
//     This allows logging events for any entity without FK constraint,
//     including events for entities that may later be archived or soft-deleted.
//
//     actor_id uses a FK to users but SET NULL — if a user account is
//     removed, the audit event is preserved with actor_id = NULL.
//
//     id is a ULID — time-ordered, so audit rows are naturally sorted
//     chronologically by primary key. No additional sort column needed.
// ---------------------------------------------------------------------------

export const auditLog = mysqlTable(
  'audit_log',
  {
    id: id(),
    orgId: varchar('org_id', { length: 26 }).references(() => organisations.id, {
      onDelete: 'set null',
    }),
    projectId: varchar('project_id', { length: 26 }).references(() => projects.id, {
      onDelete: 'set null',
    }),
    /**
     * Identifies the type of entity the event relates to.
     * Values: 'test_case' | 'test_run' | 'test_plan' | 'test_run_case' |
     *         'folder' | 'project' | 'user' | 'run_defect_link' | 'system'
     */
    entityType: varchar('entity_type', { length: 50 }).notNull(),
    /** ULID of the affected entity (matches id column of the relevant table). */
    entityId: varchar('entity_id', { length: 26 }).notNull(),
    /**
     * Dot-namespaced action identifier.
     * Examples:
     *   'case.created'        'case.updated'       'case.archived'
     *   'result.updated'      'step_result.updated'
     *   'run.created'         'run.sealed'         'run.reopened'
     *   'plan.created'        'plan.spawned_run'
     *   'defect.linked'       'defect.unlinked'
     *   'comment.created'     'comment.deleted'
     *   'user.role_updated'
     */
    action: varchar('action', { length: 100 }).notNull(),
    /** NULL for system-initiated events (e.g. automated jobs in Phase 2). */
    actorId: varchar('actor_id', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    /** Serialised previous state of the affected field(s). Nullable. */
    oldValue: json('old_value'),
    /** Serialised new state of the affected field(s). Nullable. */
    newValue: json('new_value'),
    /**
     * Structured context that does not fit old/new value model.
     * e.g. { runTitle: 'CTMS Sprint 44', caseRef: 'TC-1001' }
     */
    metadata: json('metadata'),
    /**
     * Intentionally no updated_at. This row is immutable after insert.
     * ULID id already provides time-ordering; created_at is kept for
     * explicit timestamp filtering in the Audit History view.
     */
    createdAt: timestamp('created_at', { mode: 'date' }).notNull().defaultNow(),
  },
  (t) => ({
    /** Covers entity history queries: WHERE entity_type = ? AND entity_id = ? */
    entityIdx: index('al_entity_idx').on(t.entityType, t.entityId),
    /** Covers project audit log view with date filtering. */
    projectCreatedIdx: index('al_project_created_idx').on(t.projectId, t.createdAt),
    /** Covers actor-filtered queries: who did what. */
    actorCreatedIdx: index('al_actor_created_idx').on(t.actorId, t.createdAt),
    /** Covers broad date-range queries across an org. */
    orgCreatedIdx: index('al_org_created_idx').on(t.orgId, t.createdAt),
    /** Standalone created_at for time-range scans. */
    createdAtIdx: index('al_created_at_idx').on(t.createdAt),
  }),
)

// ---------------------------------------------------------------------------
// 18. recent_views
//     Per-user recent item list powering the Cmd K palette "Recently viewed"
//     section (shown before the user types a query).
//
//     Maximum 15 rows per user enforced by the application on every insert:
//       1. UPSERT on (user_id, entity_type, entity_id) to update viewed_at.
//       2. After upsert, DELETE oldest rows if COUNT > 15.
//     This is not enforced by the DB — it is an application concern.
//
//     display_title is denormalised for instant rendering without a JOIN.
//     It should be refreshed when the entity title changes (service layer).
// ---------------------------------------------------------------------------

export const recentViews = mysqlTable(
  'recent_views',
  {
    id: id(),
    userId: varchar('user_id', { length: 26 })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    entityType: mysqlEnum('entity_type', [
      'test_case',
      'test_run',
      'test_plan',
    ]).notNull(),
    entityId: varchar('entity_id', { length: 26 }).notNull(),
    projectId: varchar('project_id', { length: 26 }).references(() => projects.id, {
      onDelete: 'cascade',
    }),
    /** Denormalised title for instant display. Update when entity title changes. */
    displayTitle: varchar('display_title', { length: 500 }).notNull(),
    /** Updated on every re-view via onUpdateNow(). Used for sort DESC to get most recent. */
    viewedAt: timestamp('viewed_at', { mode: 'date' }).notNull().defaultNow().onUpdateNow(),
  },
  (t) => ({
    /** Enables upsert on re-view: ON DUPLICATE KEY UPDATE viewed_at = NOW() */
    userEntityUnique: unique('rv_user_entity_unique').on(
      t.userId,
      t.entityType,
      t.entityId,
    ),
    /** Covers the Cmd K fetch: SELECT ... WHERE user_id = ? ORDER BY viewed_at DESC LIMIT 15 */
    userViewedAtIdx: index('rv_user_viewed_at_idx').on(t.userId, t.viewedAt),
  }),
)

// ---------------------------------------------------------------------------
// 19. saved_filters
//     User-persisted filter presets for specific views.
//     filter_state is a JSON object. Schema is view-context-specific but
//     flexible — the application owns the shape.
//
//     Example filter_state for 'cases' context:
//       { status: ['fail', 'blocked'], priority: ['critical'], assignedTo: 'ulid', folderId: 'ulid' }
//     Example filter_state for 'runs' context:
//       { status: ['active', 'stalled'], environment: 'UAT', assignedTo: 'ulid' }
// ---------------------------------------------------------------------------

export const savedFilters = mysqlTable(
  'saved_filters',
  {
    id: id(),
    userId: varchar('user_id', { length: 26 })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /**
     * Nullable — a filter can be scoped to a project or be cross-project.
     * If project_id is NULL, the filter applies globally for that view_context.
     */
    projectId: varchar('project_id', { length: 26 }).references(() => projects.id, {
      onDelete: 'cascade',
    }),
    viewContext: mysqlEnum('view_context', [
      'cases',
      'runs',
      'plans',
      'audit',
    ]).notNull(),
    name: varchar('name', { length: 255 }).notNull(),
    filterState: json('filter_state').notNull(),
    /** Pinned filters appear at the top of the filter list in the UI. */
    isPinned: boolean('is_pinned').notNull().default(false),
    ...timestamps,
  },
  (t) => ({
    userContextIdx: index('sf_user_context_idx').on(t.userId, t.viewContext),
    projectContextIdx: index('sf_project_context_idx').on(
      t.projectId,
      t.viewContext,
    ),
  }),
)

// ---------------------------------------------------------------------------
// 20. attachments_metadata
//     Phase 2 scaffold. Schema included now to avoid a breaking migration.
//     Stores S3 object metadata only. File content lives in S3 — never MySQL.
//
//     entity_type + entity_id point to any attachable entity:
//       'test_case'             → test_cases.id
//       'test_run_case'         → test_run_cases.id
//       'run_execution_comment' → run_execution_comments.id
//
//     The application enforces entity_type validity. No FK — same pattern
//     as audit_log to allow polymorphic attachments without FK complexity.
//
//     Soft-delete via is_deleted. S3 object is deleted by a background job.
// ---------------------------------------------------------------------------

export const attachmentsMetadata = mysqlTable(
  'attachments_metadata',
  {
    id: id(),
    orgId: varchar('org_id', { length: 26 }).references(() => organisations.id, {
      onDelete: 'set null',
    }),
    projectId: varchar('project_id', { length: 26 }).references(() => projects.id, {
      onDelete: 'set null',
    }),
    /** 'test_case' | 'test_run_case' | 'run_execution_comment' */
    entityType: varchar('entity_type', { length: 50 }).notNull(),
    entityId: varchar('entity_id', { length: 26 }).notNull(),
    filename: varchar('filename', { length: 500 }).notNull(),
    contentType: varchar('content_type', { length: 255 }).notNull(),
    /**
     * mode: 'number' returns a JS number from the driver.
     * Safe for file sizes up to Number.MAX_SAFE_INTEGER (~8 PB).
     */
    sizeBytes: bigint('size_bytes', { mode: 'number', unsigned: true }).notNull(),
    s3Bucket: varchar('s3_bucket', { length: 255 }).notNull(),
    s3Key: varchar('s3_key', { length: 1000 }).notNull(),
    uploadedBy: varchar('uploaded_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    uploadedAt: timestamp('uploaded_at', { mode: 'date' }).notNull().defaultNow(),
    isDeleted: boolean('is_deleted').notNull().default(false),
    deletedAt: datetime('deleted_at', { mode: 'date' }),
    deletedBy: varchar('deleted_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
  },
  (t) => ({
    entityIdx: index('am_entity_idx').on(t.entityType, t.entityId),
    projectIdx: index('am_project_idx').on(t.projectId),
    /** Lookup by bucket; s3_key is too long for a composite utf8mb4 index in MySQL. */
    s3KeyIdx: index('am_s3_key_idx').on(t.s3Bucket),
    activeAttachmentsIdx: index('am_active_attachments_idx').on(
      t.entityType,
      t.entityId,
      t.isDeleted,
    ),
  }),
)

// ---------------------------------------------------------------------------
// 21. requirements
//     First-class requirement entity, project-scoped. requirement_ref is a
//     human-readable identifier unique per project (e.g. REQ-00001), generated
//     by the service layer — same ref counter pattern as case_ref / run_ref.
//
//     source = 'local' for requirements created in Relay. 'external' is
//     reserved for future integration import (e.g. Jira) — schema-ready now
//     to avoid a breaking migration later.
//
//     Requirements are never hard-deleted at business-logic level — set
//     status = 'obsolete' instead. Case links live in requirement_case_links.
// ---------------------------------------------------------------------------

export const requirements = mysqlTable(
  'requirements',
  {
    id: id(),
    /** e.g. "REQ-00001" — unique within the project. */
    requirementRef: varchar('requirement_ref', { length: 20 }).notNull(),
    projectId: varchar('project_id', { length: 26 })
      .notNull()
      .references(() => projects.id, { onDelete: 'restrict' }),
    title: varchar('title', { length: 500 }).notNull(),
    description: text('description'),
    status: mysqlEnum('status', [
      'draft',
      'approved',
      'implemented',
      'obsolete',
    ])
      .notNull()
      .default('draft'),
    /** 'local' = created in Relay. 'external' reserved for Phase 2 import. */
    source: mysqlEnum('source', ['local', 'external']).notNull().default('local'),
    createdBy: varchar('created_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    ...timestamps,
  },
  (t) => ({
    projectRefUnique: unique('req_project_ref_unique').on(
      t.projectId,
      t.requirementRef,
    ),
    projectStatusIdx: index('req_project_status_idx').on(t.projectId, t.status),
    createdByIdx: index('req_created_by_idx').on(t.createdBy),
    updatedAtIdx: index('req_updated_at_idx').on(t.updatedAt),
  }),
)

// ---------------------------------------------------------------------------
// 22. requirement_case_links
//     Many-to-many links between requirements and test cases.
//     Mirrors the frontend Case.requirementIds relationship.
//     ON DELETE RESTRICT on test_case_id prevents hard-deleting cases that
//     are referenced by requirements — archive the case instead (same
//     pattern as test_plan_cases).
// ---------------------------------------------------------------------------

export const requirementCaseLinks = mysqlTable(
  'requirement_case_links',
  {
    id: id(),
    requirementId: varchar('requirement_id', { length: 26 })
      .notNull()
      .references(() => requirements.id, { onDelete: 'cascade' }),
    testCaseId: varchar('test_case_id', { length: 26 })
      .notNull()
      .references(() => testCases.id, { onDelete: 'restrict' }),
    linkedBy: varchar('linked_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    linkedAt: timestamp('linked_at', { mode: 'date' }).notNull().defaultNow(),
  },
  (t) => ({
    reqCaseUnique: unique('rcl_req_case_unique').on(t.requirementId, t.testCaseId),
    requirementIdIdx: index('rcl_requirement_id_idx').on(t.requirementId),
    testCaseIdIdx: index('rcl_test_case_id_idx').on(t.testCaseId),
  }),
)

// ---------------------------------------------------------------------------
// 23. defects
//     First-class defect entity, project-scoped. defect_ref is a
//     human-readable identifier unique per project (e.g. DEF-00001),
//     generated by the service layer — same ref counter pattern as case_ref.
//
//     Distinct from run_defect_links.defect_ref, which stores references to
//     EXTERNAL defect systems (e.g. "TI-4419") against a run case. This table
//     is Relay's own defect entity (frontend Defect type, source 'Local').
//     source = 'external' is reserved for future integration import.
// ---------------------------------------------------------------------------

export const defects = mysqlTable(
  'defects',
  {
    id: id(),
    /** e.g. "DEF-00001" — unique within the project. */
    defectRef: varchar('defect_ref', { length: 20 }).notNull(),
    projectId: varchar('project_id', { length: 26 })
      .notNull()
      .references(() => projects.id, { onDelete: 'restrict' }),
    title: varchar('title', { length: 500 }).notNull(),
    description: text('description'),
    status: mysqlEnum('status', [
      'open',
      'in_progress',
      'resolved',
      'closed',
    ])
      .notNull()
      .default('open'),
    /** 'local' = created in Relay. 'external' reserved for Phase 2 import. */
    source: mysqlEnum('source', ['local', 'external']).notNull().default('local'),
    createdBy: varchar('created_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    ...timestamps,
  },
  (t) => ({
    projectRefUnique: unique('def_project_ref_unique').on(t.projectId, t.defectRef),
    projectStatusIdx: index('def_project_status_idx').on(t.projectId, t.status),
    createdByIdx: index('def_created_by_idx').on(t.createdBy),
    updatedAtIdx: index('def_updated_at_idx').on(t.updatedAt),
  }),
)

// ---------------------------------------------------------------------------
// 24. defect_execution_links
//     Local defect entities linked to a specific case execution within a run
//     (mirrors the frontend CaseExecution.defects relationship).
//
//     Soft-delete: unlinked_at is set when a defect is unlinked — same
//     pattern as run_defect_links so link history is preserved for audit.
//     "Active" links are rows WHERE unlinked_at IS NULL.
// ---------------------------------------------------------------------------

export const defectExecutionLinks = mysqlTable(
  'defect_execution_links',
  {
    id: id(),
    defectId: varchar('defect_id', { length: 26 })
      .notNull()
      .references(() => defects.id, { onDelete: 'cascade' }),
    testRunCaseId: varchar('test_run_case_id', { length: 26 })
      .notNull()
      .references(() => testRunCases.id, { onDelete: 'cascade' }),
    linkedBy: varchar('linked_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
    linkedAt: timestamp('linked_at', { mode: 'date' }).notNull().defaultNow(),
    /** NULL = still linked. Set when the defect is unlinked. */
    unlinkedAt: datetime('unlinked_at', { mode: 'date' }),
    unlinkedBy: varchar('unlinked_by', { length: 26 }).references(() => users.id, {
      onDelete: 'set null',
    }),
  },
  (t) => ({
    defectIdIdx: index('del_defect_id_idx').on(t.defectId),
    testRunCaseIdIdx: index('del_test_run_case_id_idx').on(t.testRunCaseId),
    /** Covers the common query: active links for a case (WHERE unlinked_at IS NULL). */
    activeLinksIdx: index('del_active_links_idx').on(t.testRunCaseId, t.unlinkedAt),
  }),
)

// ===========================================================================
// RELATIONS
// Drizzle relations are type-level only — they do not affect the DB schema.
// They enable typed .query() with nested 'with' clauses.
// ===========================================================================

export const organisationsRelations = relations(organisations, ({ many }) => ({
  users: many(users),
  projects: many(projects),
}))

export const usersRelations = relations(users, ({ one, many }) => ({
  organisation: one(organisations, {
    fields: [users.orgId],
    references: [organisations.id],
  }),
  projectRoles: many(projectRoles),
  runAssignees: many(runAssignees),
  savedFilters: many(savedFilters),
  recentViews: many(recentViews),
}))

export const projectsRelations = relations(projects, ({ one, many }) => ({
  organisation: one(organisations, {
    fields: [projects.orgId],
    references: [organisations.id],
  }),
  createdBy: one(users, {
    fields: [projects.createdBy],
    references: [users.id],
  }),
  projectRoles: many(projectRoles),
  folders: many(folders),
  testCases: many(testCases),
  testPlans: many(testPlans),
  testRuns: many(testRuns),
  requirements: many(requirements),
  defects: many(defects),
}))

export const projectRolesRelations = relations(projectRoles, ({ one }) => ({
  project: one(projects, {
    fields: [projectRoles.projectId],
    references: [projects.id],
  }),
  user: one(users, {
    fields: [projectRoles.userId],
    references: [users.id],
  }),
  grantedBy: one(users, {
    fields: [projectRoles.grantedBy],
    references: [users.id],
    relationName: 'grantedByUser',
  }),
}))

export const foldersRelations = relations(folders, ({ one, many }) => ({
  project: one(projects, {
    fields: [folders.projectId],
    references: [projects.id],
  }),
  /**
   * Self-reference. Drizzle supports this via explicit relation names.
   * The DB-level FK is added via raw migration (not in this schema file).
   */
  parent: one(folders, {
    fields: [folders.parentId],
    references: [folders.id],
    relationName: 'folderChildren',
  }),
  children: many(folders, { relationName: 'folderChildren' }),
  testCases: many(testCases),
}))

export const testCasesRelations = relations(testCases, ({ one, many }) => ({
  project: one(projects, {
    fields: [testCases.projectId],
    references: [projects.id],
  }),
  folder: one(folders, {
    fields: [testCases.folderId],
    references: [folders.id],
  }),
  assignedTo: one(users, {
    fields: [testCases.assignedTo],
    references: [users.id],
    relationName: 'assignedCases',
  }),
  createdBy: one(users, {
    fields: [testCases.createdBy],
    references: [users.id],
    relationName: 'createdCases',
  }),
  steps: many(testCaseSteps),
  planInclusions: many(testPlanCases),
  runInstances: many(testRunCases),
  requirementLinks: many(requirementCaseLinks),
}))

export const testCaseStepsRelations = relations(testCaseSteps, ({ one }) => ({
  testCase: one(testCases, {
    fields: [testCaseSteps.testCaseId],
    references: [testCases.id],
  }),
}))

export const testPlansRelations = relations(testPlans, ({ one, many }) => ({
  project: one(projects, {
    fields: [testPlans.projectId],
    references: [projects.id],
  }),
  owner: one(users, {
    fields: [testPlans.ownerId],
    references: [users.id],
    relationName: 'ownedPlans',
  }),
  createdBy: one(users, {
    fields: [testPlans.createdBy],
    references: [users.id],
    relationName: 'createdPlans',
  }),
  cases: many(testPlanCases),
  runs: many(testRuns),
}))

export const testPlanCasesRelations = relations(testPlanCases, ({ one }) => ({
  testPlan: one(testPlans, {
    fields: [testPlanCases.testPlanId],
    references: [testPlans.id],
  }),
  testCase: one(testCases, {
    fields: [testPlanCases.testCaseId],
    references: [testCases.id],
  }),
}))

export const testRunsRelations = relations(testRuns, ({ one, many }) => ({
  project: one(projects, {
    fields: [testRuns.projectId],
    references: [projects.id],
  }),
  testPlan: one(testPlans, {
    fields: [testRuns.testPlanId],
    references: [testPlans.id],
  }),
  sealedBy: one(users, {
    fields: [testRuns.sealedBy],
    references: [users.id],
    relationName: 'sealedRuns',
  }),
  createdBy: one(users, {
    fields: [testRuns.createdBy],
    references: [users.id],
    relationName: 'createdRuns',
  }),
  cases: many(testRunCases),
  assignees: many(runAssignees),
}))

export const testRunCasesRelations = relations(testRunCases, ({ one, many }) => ({
  testRun: one(testRuns, {
    fields: [testRunCases.testRunId],
    references: [testRuns.id],
  }),
  testCase: one(testCases, {
    fields: [testRunCases.testCaseId],
    references: [testCases.id],
  }),
  assignedTo: one(users, {
    fields: [testRunCases.assignedTo],
    references: [users.id],
    relationName: 'assignedRunCases',
  }),
  executedBy: one(users, {
    fields: [testRunCases.executedBy],
    references: [users.id],
    relationName: 'executedRunCases',
  }),
  stepSnapshots: many(runCaseStepSnapshots),
  stepResults: many(runStepResults),
  defectLinks: many(runDefectLinks),
  localDefectLinks: many(defectExecutionLinks),
  comments: many(runExecutionComments),
}))

export const runCaseStepSnapshotsRelations = relations(
  runCaseStepSnapshots,
  ({ one, many }) => ({
    testRunCase: one(testRunCases, {
      fields: [runCaseStepSnapshots.testRunCaseId],
      references: [testRunCases.id],
    }),
    originalStep: one(testCaseSteps, {
      fields: [runCaseStepSnapshots.originalStepId],
      references: [testCaseSteps.id],
    }),
    stepResults: many(runStepResults),
  }),
)

export const runStepResultsRelations = relations(runStepResults, ({ one }) => ({
  testRunCase: one(testRunCases, {
    fields: [runStepResults.testRunCaseId],
    references: [testRunCases.id],
  }),
  stepSnapshot: one(runCaseStepSnapshots, {
    fields: [runStepResults.stepSnapshotId],
    references: [runCaseStepSnapshots.id],
  }),
}))

export const runAssigneesRelations = relations(runAssignees, ({ one }) => ({
  testRun: one(testRuns, {
    fields: [runAssignees.testRunId],
    references: [testRuns.id],
  }),
  user: one(users, {
    fields: [runAssignees.userId],
    references: [users.id],
  }),
}))

export const runDefectLinksRelations = relations(runDefectLinks, ({ one }) => ({
  testRunCase: one(testRunCases, {
    fields: [runDefectLinks.testRunCaseId],
    references: [testRunCases.id],
  }),
  linkedBy: one(users, {
    fields: [runDefectLinks.linkedBy],
    references: [users.id],
    relationName: 'linkedDefects',
  }),
}))

export const runExecutionCommentsRelations = relations(
  runExecutionComments,
  ({ one }) => ({
    testRunCase: one(testRunCases, {
      fields: [runExecutionComments.testRunCaseId],
      references: [testRunCases.id],
    }),
    user: one(users, {
      fields: [runExecutionComments.userId],
      references: [users.id],
    }),
  }),
)

export const recentViewsRelations = relations(recentViews, ({ one }) => ({
  user: one(users, {
    fields: [recentViews.userId],
    references: [users.id],
  }),
  project: one(projects, {
    fields: [recentViews.projectId],
    references: [projects.id],
  }),
}))

export const savedFiltersRelations = relations(savedFilters, ({ one }) => ({
  user: one(users, {
    fields: [savedFilters.userId],
    references: [users.id],
  }),
  project: one(projects, {
    fields: [savedFilters.projectId],
    references: [projects.id],
  }),
}))

export const requirementsRelations = relations(requirements, ({ one, many }) => ({
  project: one(projects, {
    fields: [requirements.projectId],
    references: [projects.id],
  }),
  createdBy: one(users, {
    fields: [requirements.createdBy],
    references: [users.id],
    relationName: 'createdRequirements',
  }),
  caseLinks: many(requirementCaseLinks),
}))

export const requirementCaseLinksRelations = relations(
  requirementCaseLinks,
  ({ one }) => ({
    requirement: one(requirements, {
      fields: [requirementCaseLinks.requirementId],
      references: [requirements.id],
    }),
    testCase: one(testCases, {
      fields: [requirementCaseLinks.testCaseId],
      references: [testCases.id],
    }),
    linkedBy: one(users, {
      fields: [requirementCaseLinks.linkedBy],
      references: [users.id],
      relationName: 'linkedRequirementCases',
    }),
  }),
)

export const defectsRelations = relations(defects, ({ one, many }) => ({
  project: one(projects, {
    fields: [defects.projectId],
    references: [projects.id],
  }),
  createdBy: one(users, {
    fields: [defects.createdBy],
    references: [users.id],
    relationName: 'createdDefects',
  }),
  executionLinks: many(defectExecutionLinks),
}))

export const defectExecutionLinksRelations = relations(
  defectExecutionLinks,
  ({ one }) => ({
    defect: one(defects, {
      fields: [defectExecutionLinks.defectId],
      references: [defects.id],
    }),
    testRunCase: one(testRunCases, {
      fields: [defectExecutionLinks.testRunCaseId],
      references: [testRunCases.id],
    }),
    linkedBy: one(users, {
      fields: [defectExecutionLinks.linkedBy],
      references: [users.id],
      relationName: 'linkedExecutionDefects',
    }),
  }),
)

// ===========================================================================
// INFERRED TYPES
// Use these throughout the application for type safety without duplication.
// ===========================================================================

export type Organisation = typeof organisations.$inferSelect
export type NewOrganisation = typeof organisations.$inferInsert

export type User = typeof users.$inferSelect
export type NewUser = typeof users.$inferInsert

export type Project = typeof projects.$inferSelect
export type NewProject = typeof projects.$inferInsert

export type ProjectRole = typeof projectRoles.$inferSelect
export type NewProjectRole = typeof projectRoles.$inferInsert

export type Folder = typeof folders.$inferSelect
export type NewFolder = typeof folders.$inferInsert

export type TestCase = typeof testCases.$inferSelect
export type NewTestCase = typeof testCases.$inferInsert

export type TestCaseStep = typeof testCaseSteps.$inferSelect
export type NewTestCaseStep = typeof testCaseSteps.$inferInsert

export type TestPlan = typeof testPlans.$inferSelect
export type NewTestPlan = typeof testPlans.$inferInsert

export type TestPlanCase = typeof testPlanCases.$inferSelect
export type NewTestPlanCase = typeof testPlanCases.$inferInsert

export type TestRun = typeof testRuns.$inferSelect
export type NewTestRun = typeof testRuns.$inferInsert

export type TestRunCase = typeof testRunCases.$inferSelect
export type NewTestRunCase = typeof testRunCases.$inferInsert

export type RunCaseStepSnapshot = typeof runCaseStepSnapshots.$inferSelect
export type NewRunCaseStepSnapshot = typeof runCaseStepSnapshots.$inferInsert

export type RunStepResult = typeof runStepResults.$inferSelect
export type NewRunStepResult = typeof runStepResults.$inferInsert

export type RunAssignee = typeof runAssignees.$inferSelect
export type NewRunAssignee = typeof runAssignees.$inferInsert

export type RunDefectLink = typeof runDefectLinks.$inferSelect
export type NewRunDefectLink = typeof runDefectLinks.$inferInsert

export type RunExecutionComment = typeof runExecutionComments.$inferSelect
export type NewRunExecutionComment = typeof runExecutionComments.$inferInsert

export type AuditLog = typeof auditLog.$inferSelect
export type NewAuditLog = typeof auditLog.$inferInsert

export type RecentView = typeof recentViews.$inferSelect
export type NewRecentView = typeof recentViews.$inferInsert

export type SavedFilter = typeof savedFilters.$inferSelect
export type NewSavedFilter = typeof savedFilters.$inferInsert

export type AttachmentMetadata = typeof attachmentsMetadata.$inferSelect
export type NewAttachmentMetadata = typeof attachmentsMetadata.$inferInsert

export type Requirement = typeof requirements.$inferSelect
export type NewRequirement = typeof requirements.$inferInsert

export type RequirementCaseLink = typeof requirementCaseLinks.$inferSelect
export type NewRequirementCaseLink = typeof requirementCaseLinks.$inferInsert

export type Defect = typeof defects.$inferSelect
export type NewDefect = typeof defects.$inferInsert

export type DefectExecutionLink = typeof defectExecutionLinks.$inferSelect
export type NewDefectExecutionLink = typeof defectExecutionLinks.$inferInsert
